Updated git pre-commit hook

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -18,9 +18,16 @@ fi
 
 # Run unit tests
 echo "Running yarn test:unit..."
-yarn test:unit
+yarn test
 if [ $? -ne 0 ]; then
   echo "Unit tests failed. Please fix the issues before committing."
+  exit 1
+fi
+
+echo "Running yarn test:e2e..."
+yarn test:e2e
+if [ $? -ne 0 ]; then
+  echo "E2E tests failed. Please fix the issues before committing."
   exit 1
 fi
 
