Added "All required tests passed or skipped" check to CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -15,3 +15,19 @@ jobs:
     uses: ./.github/workflows/lint-and-test.yml
     with:
       node-version: ${{ matrix.node }}
+  job_required_tests:
+    name: All required tests passed or skipped
+    needs:
+      [
+        lint-and-test
+      ]
+    if: always()
+    runs-on: ubuntu-latest
+    steps:
+      - name: Output needs
+        run: echo "${{ toJson(needs) }}"
+
+      - name: Check if any required jobs failed or been cancelled
+        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
+        run: |
+          echo "One of the dependent jobs have failed or been cancelled. You may need to re-run it." && exit 1
